# Generated by Django 4.2.1 on 2023-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.BigIntegerField(null=True, unique=True)),
                ('original_title', models.CharField(max_length=250, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('date_published', models.DateField(null=True)),
                ('language', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('reviews_from_user', models.IntegerField(null=True)),
                ('reviews_from_critics', models.IntegerField(null=True)),
                ('genre', models.ManyToManyField(related_name='MovieData_genre', to='MovieDataApp.genre')),
            ],
        ),
    ]
