# Generated by Django 4.2.1 on 2023-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='duration',
            field=models.BigIntegerField(null=True),
        ),
    ]
