# Generated by Django 4.2.1 on 2023-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDataApp', '0002_moviedata_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
