# Generated by Django 4.2.1 on 2023-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreName',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
